before_install:
  # Install various build dependencies. We use `travis_retry` because `go get`
  # will occasionally fail intermittently.

  # The testify require framework is used for assertions in the test suite
  - travis_retry go get -u github.com/stretchr/testify/require
  - travis_retry go get -u gopkg.in/h2non/gock.v1

go:
  - "1.13.x"
  - tip

language: go

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - make test

sudo: false
